import { BrowserRouter, Route, Routes } from "react-router-dom";
import { AuthProvider } from "./context/AuthContext";
import { ProtectedRoute, RoleRoute } from "./routes/RouteGuards";
import { Landing, Jobs, JobDetail, Login, NotFound, Register, SetPassword } from "./pages/Public";
import {CandidateApplications,CandidateApplicationDetail,CandidateCV,CandidateDashboard,CandidateJobDetail,CandidateJobs,CandidateProfile,CandidateShell}from"./pages/Candidate";
import {RecruiterApplicationDetail,RecruiterApplications,RecruiterDashboard,RecruiterJobDetail,RecruiterJobs,RecruiterShell}from"./pages/Recruiter";
import {AdminDashboard,AdminJobDetail,AdminJobNew,AdminJobs,AdminRecruiters,AdminShell}from"./pages/Admin";
import {AdminApplicationDetail,AdminApplications,AdminAssignments}from"./pages/AdminD2";
const candidate=node=><ProtectedRoute><RoleRoute role="candidate"><CandidateShell>{node}</CandidateShell></RoleRoute></ProtectedRoute>;
const recruiter=node=><ProtectedRoute><RoleRoute role="recruiter"><RecruiterShell>{node}</RecruiterShell></RoleRoute></ProtectedRoute>;
const admin=node=><ProtectedRoute><RoleRoute role="admin"><AdminShell>{node}</AdminShell></RoleRoute></ProtectedRoute>;
function App(){return <BrowserRouter><AuthProvider><Routes><Route path="/" element={<Landing/>}/><Route path="/jobs" element={<Jobs/>}/><Route path="/jobs/:jobId" element={<JobDetail/>}/><Route path="/login" element={<Login/>}/><Route path="/register" element={<Register/>}/><Route path="/set-password" element={<SetPassword/>}/><Route path="/candidate" element={candidate(<CandidateDashboard/>)}/><Route path="/candidate/profile" element={candidate(<CandidateProfile/>)}/><Route path="/candidate/cv" element={candidate(<CandidateCV/>)}/><Route path="/candidate/jobs" element={candidate(<CandidateJobs/>)}/><Route path="/candidate/jobs/:jobId" element={candidate(<CandidateJobDetail/>)}/><Route path="/candidate/applications" element={candidate(<CandidateApplications/>)}/><Route path="/candidate/applications/:applicationId" element={candidate(<CandidateApplicationDetail/>)}/><Route path="/recruiter" element={recruiter(<RecruiterDashboard/>)}/><Route path="/recruiter/jobs" element={recruiter(<RecruiterJobs/>)}/><Route path="/recruiter/jobs/:jobId" element={recruiter(<RecruiterJobDetail/>)}/><Route path="/recruiter/applications" element={recruiter(<RecruiterApplications/>)}/><Route path="/recruiter/applications/:applicationId" element={recruiter(<RecruiterApplicationDetail/>)}/><Route path="/admin" element={admin(<AdminDashboard/>)}/><Route path="/admin/recruiters" element={admin(<AdminRecruiters/>)}/><Route path="/admin/jobs" element={admin(<AdminJobs/>)}/><Route path="/admin/jobs/new" element={admin(<AdminJobNew/>)}/><Route path="/admin/jobs/:jobId" element={admin(<AdminJobDetail/>)}/><Route path="/admin/assignments" element={admin(<AdminAssignments/>)}/><Route path="/admin/applications" element={admin(<AdminApplications/>)}/><Route path="/admin/applications/:applicationId" element={admin(<AdminApplicationDetail/>)}/><Route path="*" element={<NotFound/>}/></Routes></AuthProvider></BrowserRouter>}

export default App;
